spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Blog
    username: root
    password: admin123
  redis:
    host: localhost
    port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucketName: ${BUCKET_NAME}